import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    const style = document.createElement('style');
    style.textContent = `
      *,
      *::before,
      *::after {
        transition-duration: 0s !important;
        animation-duration: 0s !important;
        scroll-behavior: auto !important;
      }
      .cursor-follow,
      .cursor-dot {
        display: none !important;
      }
    `;
    document.head.appendChild(style);
  });
  await page.emulateMedia({ reducedMotion: 'reduce' });
});

test.describe('Logi-Ink Smoke Suite', () => {
  test('primary navigation routes between key pages', async ({ page }) => {
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    const servicesLink = page.locator('nav.navbar a[href="services.html"]').first();
    await servicesLink.waitFor({ state: 'visible' });
    await servicesLink.click({ force: true, timeout: 10_000 });
    await page.waitForURL('**/services.html', { timeout: 15_000 });

    await expect(page.locator('main')).toContainText('What We Offer');

    const contactLink = page.locator('nav.navbar a[href="contact.html"]').first();
    await contactLink.waitFor({ state: 'visible' });
    await contactLink.click({ force: true, timeout: 10_000 });
    await page.waitForURL('**/contact.html', { timeout: 15_000 });

    await expect(page.locator('#contactForm')).toBeVisible();
  });

  test('service modals open and close via the services grid', async ({ page }) => {
    await page.goto('/services.html');

    const firstServiceCard = page.locator('.service-card-square').first();
    await firstServiceCard.getByRole('button', { name: 'Learn More' }).click();

    const modal = page.locator('#modal-web-dev');
    await expect(modal).toHaveClass(/active/);
    await expect(modal).toBeVisible();

    await modal.locator('.modal-close').click();
    await expect(modal).not.toHaveClass(/active/);
  });

  test('contact form completes happy-path submission', async ({ page }) => {
    await page.goto('/contact.html');

    await page.evaluate(() => {
      window.Math.random = () => 0.5;
    });

    await page.fill('#name', 'Playwright Smoke');
    await page.fill('#email', 'qa+playwright@logi-ink.com');
    await page.fill('#subject', 'Automated QA Smoke Test');
    await page.fill('#message', 'This is a smoke test message generated by Playwright.');

    await page.click('#submitButton');

    const successToast = page.locator('.toast.success');
    await expect(successToast).toBeVisible({ timeout: 10_000 });
    await expect(successToast).toContainText('Thank you for your message');
  });
});

